### PR TITLE
feat: Add account ID to GuardDuty event notification

### PR DESCRIPTION
**Pull request by bruno**
## Description

Always show the AWS AccountID that the GuardDuty event is related to.

I've modified the sample events and messages to add a bogus `accountId`. Running the `pipenv` commands as per the `README` made some formatting changes on `mylambda.py`, so I am leaving that as suggested by that run.

The snapshots also needed updating to reflect the fact that we now have an AccountID in the GuardDuty event/message.

It's my first contribution to this repo, so apologies in advance 😄 

## Motivation and Context

This PR was motivated by the same reasoning I saw in https://github.com/terraform-aws-modules/terraform-aws-notify-slack/issues/164. We are using this module to send notifications from multiple AWS accounts to Slack and not having the AccountID visible in the notification was bugging us, as it makes the investigation slightly more tedious.

In order to add this attribute, I validated that even on a single (newly created) AWS account, the GuardDuty event always contains an `AccountID` attribute. The AWS documentation https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_findings_cloudwatch.html seems to indicate this too. This was achieved by triggering the sample events from the AWS console.

## How Has This Been Tested?

- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by bruno** [comment]
I am confused by the failing tests, as I ran the `pre-commit run -a` locally:

```Shell
❯ TAG=latest
❯ docker run -e "USERID=$(id -u):$(id -g)" -v $(pwd):/lint -w /lint ghcr.io/antonbabenko/pre-commit-terraform:$TAG run -a
Unable to find image 'ghcr.io/antonbabenko/pre-commit-terraform:latest' locally
[...]
Digest: sha256:64ce1e4b99d85497fe646db0724669039b079b45fa8cd503b4dc23dbdca490ae
Status: Downloaded newer image for ghcr.io/antonbabenko/pre-commit-terraform:latest
[INFO] Initializing environment for https://github.com/antonbabenko/pre-commit-terraform.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Terraform fmt............................................................Passed
Terraform validate.......................................................Passed
Terraform docs...........................................................Passed
Terraform validate with tflint...........................................Passed
check for merge conflicts................................................Passed
fix end of files.........................................................Passed
```

Am I missing something?

**Comment by bryantbiggs** [comment]
it looks like this workflow didn't get updated yet. If you update the same file from here https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/.github/workflows/pre-commit.yml in this PR it should run the tests successfully

**Review by bryantbiggs — APPROVED** [review]

**Comment by bruno** [comment]
Sorry @bryantbiggs just noticed that GitHub was complaining about `master` having moved forward underneath me, so I have fixed that. Thank you for approving the PR 🙇

**Comment by antonbabenko** [comment]
This PR is included in version 5.6.0 :tada:

**Pull request merged**
