### PR TITLE
Loading incoming event into dictionary if from Cloudwatch. (#24)

### PR DESCRIPTION
**Pull request by ryron01**

### CODE REVIEW

**Comment by antonbabenko** [comment]
Thanks for the PR and investigation!

I believe you tried it, so could you please update an example, where the same lambda function will be used for both - cloudwatch events and other types (eg, SNS).

Also, have you found some confirmation that AWS submits messages in different format? It would be great to add to README.

**Comment by ryron01** [comment]
Yes, I did test it. I used a simple event, then I tested again using an example event I found. (see below) Effectively I reverted the behavior back to 1.10.0 when the event is coming from CloudWatch using the existing logic.  

I don't have any CloudWatch Alarms configured, but I did find two examples that I used.  The format is basically the same but the message content is escaped out JSON. 

`{
  "Records": [
    {
      "EventSource": "aws:sns",
      "EventVersion": "1.0",
      "EventSubscriptionArn": "arn:aws:sns:eu-west-1:000000000000:cloudwatch-alarms:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "Sns": {
        "Type": "Notification",
        "MessageId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "TopicArn": "arn:aws:sns:eu-west-1:000000000000:cloudwatch-alarms",
        "Subject": "ALARM: \"Example alarm name\" in EU - Ireland",
        "Message": "{\"AlarmName\":\"Example alarm name\",\"AlarmDescription\":\"Example alarm description.\",\"AWSAccountId\":\"000000000000\",\"NewStateValue\":\"ALARM\",\"NewStateReason\":\"Threshold Crossed: 1 datapoint (10.0) was greater than or equal to the threshold (1.0).\",\"StateChangeTime\":\"2017-01-12T16:30:42.236+0000\",\"Region\":\"EU - Ireland\",\"OldStateValue\":\"OK\",\"Trigger\":{\"MetricName\":\"DeliveryErrors\",\"Namespace\":\"ExampleNamespace\",\"Statistic\":\"SUM\",\"Unit\":null,\"Dimensions\":[],\"Period\":300,\"EvaluationPeriods\":1,\"ComparisonOperator\":\"GreaterThanOrEqualToThreshold\",\"Threshold\":1.0}}",
        "Timestamp": "2017-01-12T16:30:42.318Z",
        "SignatureVersion": "1",
        "Signature": "Cg==",
        "SigningCertUrl": "https://sns.eu-west-1.amazonaws.com/SimpleNotificationService-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.pem",
        "UnsubscribeUrl": "https://sns.eu-west-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:eu-west-1:000000000000:cloudwatch-alarms:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "MessageAttributes": {}
      }
    }
  ]
}`

Another example here:  https://cloudonaut.io/send-cloudwatch-alarms-to-slack-with-aws-lambda/

**Comment by yujunz** [comment]
+1

It works for me :-)

**Comment by antonbabenko** [comment]
[v1.13.0](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/releases/v1.13.0) has been released with _similar_ fix.

**Pull request closed without merging**
