### PR TITLE
feat: Added path input variable for lambda module IAM role 

### PR DESCRIPTION
**Pull request by onymbuk**
## Description
Role path is needed for IAM role created by lambda module

## Motivation and Context
We use permission boundaries tied to IAM role path in our environment. This is required for us

## Breaking Changes
No breaking change

## How Has This Been Tested?
This has been tested on this branch

### CODE REVIEW

**Comment by bryantbiggs** [comment]
thanks @onymbuk - are you able to update the docs by running `pre-commit run -a`?

**Comment by onymbuk** [comment]
> thanks @onymbuk - are you able to update the docs by running `pre-commit run -a`?

**Review by bryantbiggs — APPROVED** [review]
@antonbabenko 👍

**Comment by antonbabenko** [comment]
This PR is included in version 4.19.0 :tada:

**Pull request merged**
