### PR TITLE
feat: call slack channel if state is alarm

### PR DESCRIPTION
**Pull request by fmarcolino**
## Description
This pr will add `@channel` message when state alarm is ALARM, if variable is true!

## Motivation and Context
I need that this module creates cloudwatch alert message with channel command, when enabled.

If the alert is very important, for example, should call all people in the channel to resolve this. Actually, doesn't do.

## Breaking Changes

No break. A new variable contains default value, and it will hold the current behaviour.

## How Has This Been Tested?

Terraform apply done
Two modules (one with channel Infrastructure alerts, and other without channel - control alerts)
image

Tested
1 - Infrastructure alerts (need channel)
image
image

2 - Control Alerts (no need without channel)
image

Environment
> Terraform v0.11.14
> + provider.archive v1.3.0
> + provider.aws v2.70.0
> + provider.external v1.2.0
> + provider.null v2.1.2
> + provider.template v2.1.2

This change will create a environment variable within function, only. No problems with other areas of code.

### CODE REVIEW

**Comment by fmarcolino** [comment]
@antonbabenko Save us, please :pray:

**Comment by AndrewFarley** [comment]
This is a neat idea, but it might be better to allow the option to specify what to alert, not just blatantly @channel.  Eg: to @ an group (eg: @devops) or to @ an individual for smaller orgs that only have one ops/devops person.  I think this could be accomplished by changing the variable `channel_if_alarm` into `append_if_alarm` and the variable is an string which is empty by default.  This way users could still put @channel in to that variable if they wanted to channel, but it gives them a lot more flexibility in whom to alarm (instead of the entire channel).

Thoughts @fmarcolino ?

**Review by AndrewFarley — APPROVED** [review]
Reviewed code and reformatting, looks good to me.  However I did not functionally test this

**Comment by antonbabenko** [comment]
Looked pretty good until I changed the base branch to `master` (it was `terraform011` before). Please apply the necessary changes and I will make another review shortly after. Thanks!

**Comment by AndrewFarley** [comment]
Un-stale this please, still want this

**Pull request closed without merging**
