### PR TITLE
fix: Remove data resource for sns topic to avoid race condition

### PR DESCRIPTION
**Pull request by bushong1**
##  Description

Remove the SNS Topic Data Resource and instead craft the SNS Topic ARN as a string. 

## Motivation and Context
Data Resources are evaluated before any code is executed, so if a single terraform apply intends to create an SNS topic _and_ create this module, the apply will fail because the data resource cannot resolve.  Avoiding the use of data resources by deriving the SNS manually corrects the issue in this case. 
 #46 

## Breaking Changes
This should not affect any existing deployment aside from seeing a change from removing a data resource.

## How Has This Been Tested?
Using the examples

### CODE REVIEW

**Comment by razorsedge** [comment]
This PR works for me.

**Comment by razorsedge** [comment]
@antonbabenko Why has this PR not been reviewed? `create_sns_topic = false` with `sns_topic_name       = blah` is broken if `blah` does not already exist.

**Comment by antonbabenko** [comment]
> Why has this PR not been reviewed?

Lack of time and various other priorities.

Want to support? Consider sponsoring me on GitHub.

**Comment by antonbabenko** [comment]
Finally! :)

[v4.12.0](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/releases/v4.12.0) has been just released.

**Pull request merged**
