### PR TITLE
need to convert from json string to dict when extracting message from event

### PR DESCRIPTION
**Pull request by invertigo**
The value of `event['Records'][0]['Sns']['Message']` is a json string, not a dictionary.  I was getting this error prior to making the change:

    string indices must be integers: TypeError
    Traceback (most recent call last):
    File "/var/task/notify_slack.py", line 79, in lambda_handler
    notify_slack(subject, message, region)
    File "/var/task/notify_slack.py", line 64, in notify_slack
    payload['text'] = "AWS CloudWatch notification - " + message["AlarmName"]
    TypeError: string indices must be integers

### CODE REVIEW

**Comment by antonbabenko** [comment]
@invertigo We went back and forth with a similar change I believe. See #24, #23, #25 and maybe few more.

Can somebody also take a look at this/these?

**Comment by invertigo** [comment]
> @invertigo We went back and forth with a similar change I believe. See #24, #23, #25 and maybe few more.
> 
> Can somebody also take a look at this/these?

I updated the patch here based on the changes you linked - should take care of most cases and provide a meaningful error if not.

**Comment by antonbabenko** [comment]
@invertigo 🤞 Ok, let's merge and see.

@ryron01 Do you have an opinion on this?

**Comment by antonbabenko** [comment]
[v1.13.0](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/releases/v1.13.0) has been released.

**Pull request merged**
